/** English fallbacks for categories not in GEN (excludes flags & economics — already in GEN). */
export const FALLBACK_EN = {
  theater: [
    { q: "Who wrote Hamlet?", o: ["Shakespeare", "Molière", "Ibsen", "Shaw"], a: 0 },
    { q: "The Globe Theatre is linked to?", o: ["Paris", "London", "Rome", "Athens"], a: 1 },
    { q: "La Scala opera house is in?", o: ["Rome", "Milan", "Venice", "Naples"], a: 1 },
    { q: "The Blue Bird playwright?", o: ["Maeterlinck", "Shaw", "Ibsen", "Chekhov"], a: 0 },
    { q: "Traditional Chinese opera form often called?", o: ["Kabuki", "Peking opera", "Noh", "Kathak"], a: 1 },
    { q: "Wayang shadow puppetry is famous in?", o: ["China", "Indonesia", "India", "Turkey"], a: 1 },
    { q: "Antigone was written by?", o: ["Sophocles", "Euripides", "Aeschylus", "Aristotle"], a: 0 },
    { q: "Broadway is a theatre district in?", o: ["Los Angeles", "New York", "Chicago", "Boston"], a: 1 },
  ],
  landmarks: [
    { q: "Eiffel Tower city?", o: ["London", "Paris", "Berlin", "Madrid"], a: 1 },
    { q: "Statue of Liberty was a gift from France to?", o: ["Canada", "United States", "Australia", "Brazil"], a: 1 },
    { q: "Great Wall of China was built mainly for?", o: ["Trade", "Defense", "Irrigation", "Tourism"], a: 1 },
    { q: "Colosseum is in?", o: ["Athens", "Rome", "Istanbul", "Cairo"], a: 1 },
    { q: "India Gate is in?", o: ["Delhi", "Mumbai", "Kolkata", "Bangalore"], a: 0 },
    { q: "Golden Gate Bridge city?", o: ["New York", "Los Angeles", "San Francisco", "Chicago"], a: 2 },
    { q: "Machu Picchu country?", o: ["Mexico", "Peru", "Chile", "Colombia"], a: 1 },
    { q: "Arc de Triomphe city?", o: ["London", "Paris", "Berlin", "Vienna"], a: 1 },
  ],
  culture: [
    { q: "Rio Carnival is famous in?", o: ["Argentina", "Brazil", "Chile", "Venezuela"], a: 1 },
    { q: "UN Arabic Language Day is?", o: ["18 December", "21 February", "15 September", "4 June"], a: 0 },
    { q: "Halloween traces roots to?", o: ["Ancient Celtic festivals", "Roman only", "Chinese only", "Indian only"], a: 0 },
    { q: "Diwali is a major festival in?", o: ["Buddhism only", "Hinduism", "Islam only", "Shinto only"], a: 1 },
    { q: "Samba is strongly tied to?", o: ["Argentina", "Brazil", "Cuba", "Mexico"], a: 1 },
    { q: "Kimono is traditional dress from?", o: ["China", "Korea", "Japan", "Vietnam"], a: 2 },
    { q: "International Museum Day?", o: ["18 May", "12 April", "7 March", "1 November"], a: 0 },
    { q: "K-pop refers to pop culture from?", o: ["Japan", "South Korea", "China", "Thailand"], a: 1 },
  ],
  politics: [
    { q: "UN headquarters main site?", o: ["Geneva", "New York", "The Hague", "Vienna"], a: 1 },
    { q: "Permanent UNSC members (five)?", o: ["NATO only", "China France Russia UK USA", "EU only", "G20"], a: 1 },
    { q: "EU institutional hub often cited?", o: ["Paris", "Brussels", "Berlin", "Rome"], a: 1 },
    { q: "Cold War mainly between?", o: ["US and Japan", "US and Soviet Union", "France and Germany", "China and India"], a: 1 },
    { q: "NATO was founded for?", o: ["Trade", "Collective defense", "Environment", "Health"], a: 1 },
    { q: "First female UK Prime Minister?", o: ["Thatcher", "Merkel", "May", "Truss"], a: 0 },
    { q: "Soviet Union dissolved in?", o: ["1989", "1991", "1995", "2001"], a: 1 },
    { q: "OPEC focuses on?", o: ["Oil", "Natural gas only", "Nuclear", "Coal"], a: 0 },
  ],
  religion: [
    { q: "Second holiest city in Islam after Mecca?", o: ["Jerusalem", "Medina", "Damascus", "Baghdad"], a: 1 },
    { q: "Bhagavad Gita is sacred in?", o: ["Buddhism", "Hinduism", "Sikhism", "Jainism"], a: 1 },
    { q: "Easter celebrates?", o: ["Birth", "Resurrection", "Ascension", "Baptism"], a: 1 },
    { q: "Kaaba is in?", o: ["Medina", "Mecca", "Taif", "Jeddah"], a: 1 },
    { q: "Pope is head of largest Christian branch?", o: ["Eastern Orthodox", "Protestant", "Catholic", "Anglican"], a: 2 },
    { q: "Buddhism originated in?", o: ["China", "India", "Japan", "Thailand"], a: 1 },
    { q: "Jewish Sabbath day?", o: ["Friday", "Saturday", "Sunday", "Monday"], a: 1 },
    { q: "Four holy books in Islam include?", o: ["Gospels Torah Psalms Quran", "Vedas only", "Tripitaka only", "Tripitaka"], a: 0 },
  ],
  media: [
    { q: "Pulitzer Prize domain?", o: ["Sports", "Journalism and literature", "Medicine", "Physics"], a: 1 },
    { q: "CNN originally headquartered in?", o: ["New York", "Atlanta", "Washington", "Los Angeles"], a: 1 },
    { q: "BBC is?", o: ["American", "British", "Australian", "Canadian"], a: 1 },
    { q: "Podcast is?", o: ["Digital audio show", "Live video only", "Newspaper", "SMS app"], a: 0 },
    { q: "Reuters news agency HQ?", o: ["Paris", "London", "Berlin", "New York"], a: 1 },
    { q: "Fake news common English term?", o: ["Deep fake only", "Fake news", "Spam only", "Clickbait only"], a: 1 },
    { q: "YouTube founded around?", o: ["2003", "2005", "2007", "2010"], a: 1 },
    { q: "LinkedIn focuses on?", o: ["Games", "Jobs and careers", "Cooking", "Sports"], a: 1 },
  ],
  customs: [
    { q: "Eid al-Adha commemorates?", o: ["Birth", "Sacrifice of Ishmael story", "Migration", "Isra"], a: 1 },
    { q: "Tea as hospitality is common in?", o: ["Only Brazil", "Japan UK China and more", "Only Canada", "Only Australia"], a: 1 },
    { q: "Handshake less common in some cultures; Japan often uses?", o: ["High-five", "Bow", "Hug", "Salute"], a: 1 },
    { q: "Christmas celebrated on?", o: ["November", "25 December (often)", "January only", "April only"], a: 1 },
    { q: "Arabic coffee often served with?", o: ["Milk", "Dates", "Lemon", "Soda"], a: 1 },
    { q: "Henna at celebrations is common in?", o: ["Only Europe", "South Asia Middle East", "Only Arctic", "Only Antarctica"], a: 1 },
    { q: "Ramadan is month of?", o: ["Feasting only", "Fasting and reflection", "Harvest only", "New Year only"], a: 1 },
    { q: "Wedding rings worn on left ring finger tradition in many?", o: ["Western cultures", "None", "Only children", "Only monks"], a: 0 },
  ],
  space: [
    { q: "First human in space?", o: ["Armstrong", "Yuri Gagarin", "Aldrin", "Glenn"], a: 1 },
    { q: "Closest planet to the Sun?", o: ["Venus", "Mercury", "Mars", "Earth"], a: 1 },
    { q: "Planet famous for rings?", o: ["Jupiter", "Saturn", "Uranus", "Neptune"], a: 1 },
    { q: "James Webb Space Telescope mainly?", o: ["Visible only", "Infrared", "X-ray only", "Radio only"], a: 1 },
    { q: "Milky Way shape?", o: ["Elliptical", "Spiral", "Irregular", "Spherical"], a: 1 },
    { q: "Sputnik 1 was first?", o: ["Human flight", "Artificial satellite", "Moon landing", "Space station"], a: 1 },
    { q: "NASA is?", o: ["Russian", "American", "Chinese", "European"], a: 1 },
    { q: "Moon orbit period around Earth ~?", o: ["7 days", "27 days", "365 days", "90 days"], a: 1 },
  ],
  animals: [
    { q: "Fastest bird in a dive (peregrine)?", o: ["Eagle", "Peregrine falcon", "Owl", "Pigeon"], a: 1 },
    { q: "Giant panda diet mainly?", o: ["Meat", "Bamboo", "Fish", "Honey"], a: 1 },
    { q: "Only mammal capable of true sustained flight?", o: ["Mouse", "Bat", "Squirrel", "Lemur"], a: 1 },
    { q: "Blue whale eats mainly?", o: ["Large fish", "Krill", "Seaweed", "Birds"], a: 1 },
    { q: "Sloth is slow partly due to?", o: ["Laziness only", "Very low metabolism", "Illness", "Age"], a: 1 },
    { q: "Giraffe tongue is?", o: ["Short", "Very long", "None", "Thick only"], a: 1 },
    { q: "Crocodile habitat?", o: ["Arctic", "Wetlands and water", "Dry desert", "Mountains"], a: 1 },
    { q: "Bees waggle dance communicates?", o: ["Fun", "Food location", "Fear", "Mating"], a: 1 },
  ],
  fashion: [
    { q: "Chanel founded in?", o: ["Italy", "France", "UK", "USA"], a: 1 },
    { q: "Blue jeans mass popularized by?", o: ["Levi Strauss", "Nike", "Adidas", "Zara"], a: 0 },
    { q: "Typical Western suit pieces?", o: ["Three always", "Jacket and trousers", "Four", "One"], a: 1 },
    { q: "Sari traditional in?", o: ["Japan", "India", "Korea", "China"], a: 1 },
    { q: "Louis Vuitton known for?", o: ["Cars", "Luxury leather goods", "Sports", "Phones"], a: 1 },
    { q: "Adidas founded in?", o: ["USA", "Germany", "UK", "France"], a: 1 },
    { q: "Runway fashion shows highlight?", o: ["Food", "New collections", "Cars", "Software"], a: 1 },
    { q: "Haute couture means?", o: ["Mass market", "High-end custom fashion", "Uniforms", "Sportswear only"], a: 1 },
  ],
  business: [
    { q: "IPO means?", o: ["Initial public offering", "Private buyout", "Merger", "Bankruptcy"], a: 0 },
    { q: "Steve Jobs co-founded?", o: ["Microsoft", "Apple", "Google", "Amazon"], a: 1 },
    { q: "LLC protects?", o: ["Employees only", "Owners from unlimited debt", "Government", "Banks only"], a: 1 },
    { q: "Franchise grants?", o: ["Closure", "Brand and system license", "Liquidation", "Tax exemption"], a: 1 },
    { q: "Acquisition means?", o: ["Buying another company", "Selling a branch", "Layoffs", "Bond issue"], a: 0 },
    { q: "Business model describes?", o: ["Building", "How a firm makes money", "Payroll", "Logo"], a: 1 },
    { q: "Free shipping often aims to?", o: ["Reduce sales", "Boost conversions", "Raise taxes", "Stop ads"], a: 1 },
    { q: "Venture capital invests in?", o: ["Only governments", "Startups with growth risk", "Only banks", "Only farms"], a: 1 },
  ],
  gaming: [
    { q: "Minecraft originally by?", o: ["Mojang", "Blizzard", "EA", "Ubisoft"], a: 0 },
    { q: "Mario franchise owner?", o: ["Sony", "Nintendo", "Microsoft", "Sega"], a: 1 },
    { q: "Fortnite by?", o: ["Activision", "Epic Games", "Rockstar", "Valve"], a: 1 },
    { q: "PlayStation 2 launched ~?", o: ["1998", "2000", "2005", "2010"], a: 1 },
    { q: "World of Warcraft is?", o: ["MMORPG", "Racing", "FPS only", "Puzzle"], a: 0 },
    { q: "PUBG genre?", o: ["Battle royale", "Puzzle", "Flight sim", "Soccer"], a: 0 },
    { q: "Steam is a?", o: ["Valve game store", "Microsoft OS", "Apple phone", "Google search"], a: 0 },
    { q: "3DS handheld by?", o: ["Sony", "Nintendo", "Sega", "Atari"], a: 1 },
  ],
  cars: [
    { q: "Model T helped?", o: ["Luxury only", "Mass car ownership", "Planes", "Trains"], a: 1 },
    { q: "Toyota from?", o: ["Korea", "Japan", "China", "Germany"], a: 1 },
    { q: "Mercedes-Benz HQ city?", o: ["Munich", "Stuttgart", "Berlin", "Frankfurt"], a: 1 },
    { q: "Tesla known for?", o: ["Diesel only", "Electric vehicles", "Steam", "Bicycles"], a: 1 },
    { q: "ABS helps?", o: ["Go faster", "Prevent wheel lock when braking", "Save fuel", "Cool engine"], a: 1 },
    { q: "Lamborghini began as?", o: ["Planes", "Tractors then supercars", "Ships", "Bikes"], a: 1 },
    { q: "Self-driving cars rely on?", o: ["Stone", "Sensors and AI", "Wood", "Wind"], a: 1 },
    { q: "Ferrari logo animal?", o: ["Bull", "Prancing horse", "Lion", "Eagle"], a: 1 },
  ],
  tribes: [
    { q: "In Arabian context, a tribe is usually a?", o: ["Historical kinship-based social grouping", "Modern stock exchange", "Type of currency", "Administrative district only"], a: 0 },
    { q: "The term fakhadh commonly means?", o: ["Sub-lineage branch within a larger tribal structure", "A capital city", "A legal code", "A banking method"], a: 0 },
    { q: "A shared value in Kuwaiti/Saudi tribal heritage is?", o: ["Hospitality and guest protection", "No guest reception", "Climate zoning", "Import tariffs"], a: 0 },
    { q: "Historic tribal migration in central Arabia was often driven by?", o: ["Water, pasture, and trade routes", "Polar ice", "Subway expansion", "Atlantic shipping lanes"], a: 0 },
    { q: "A Kuwaiti diwaniya traditionally serves as?", o: ["Social guest hall and discussion forum", "Industrial warehouse", "Rail terminal", "Stadium"], a: 0 },
    { q: "Nakhwa in tribal usage often implies?", o: ["Solidarity, honor, and readiness to support", "A tax bracket", "A coin type", "A visa category"], a: 0 },
    { q: "For accurate tribal history work, best practice is?", o: ["Use multiple corroborated sources", "Use one anonymous post", "Rely on rumor only", "Avoid written material"], a: 0 },
    { q: "In tribal studies, lineage and custom are best described as?", o: ["Lineage = descent; custom = social practice", "Exactly the same concept", "Both weather terms", "Both currency terms"], a: 0 },
  ],
  health: [
    { q: "Daily fluid intake guideline ~?", o: ["0.5 L", "~2 L including drinks", "5 L", "10 L"], a: 1 },
    { q: "Adult sleep typically?", o: ["3-4 h", "7-9 h", "12 h", "1 h"], a: 1 },
    { q: "Vitamin D important for?", o: ["Hair only", "Bones and immunity", "Nails only", "Skin only"], a: 1 },
    { q: "Resting heart rate adult ~?", o: ["40", "60-100 bpm", "150", "20"], a: 1 },
    { q: "Type 2 diabetes prevention includes?", o: ["Inactivity", "Diet and exercise", "Smoking", "Sugar only"], a: 1 },
    { q: "Vaccines train?", o: ["Lymph production schedule", "Immune system", "Digestive enzyme mix", "Resting heart rhythm"], a: 1 },
    { q: "Hypertension called silent because?", o: ["Loud", "Often no symptoms", "Ear pain", "Instant pain"], a: 1 },
    { q: "Handwashing reduces?", o: ["Sunburn", "Infectious spread", "Lightning", "Earthquakes"], a: 1 },
  ],
  travel: [
    { q: "Jet lag caused by?", o: ["Hunger", "Time zone shift", "Rain", "Hotel height"], a: 1 },
    { q: "eVisa means?", o: ["Plastic card", "Electronic visa before travel", "Plane ticket", "Insurance"], a: 1 },
    { q: "UTC reference meridian?", o: ["Paris", "Greenwich", "New York", "Tokyo"], a: 1 },
    { q: "Lost luggage handled via?", o: ["Bank", "Airline baggage desk", "Hotel only", "Police only"], a: 1 },
    { q: "Budget airlines cut costs by?", o: ["Eliminating maintenance", "Fees and efficiency", "Government fuel grants", "Single-class wide-body only"], a: 1 },
    { q: "Travel insurance often covers?", o: ["Routine wardrobe purchase", "Trip cancel and medical emergency", "Visa renewal fees", "Airport lounge upgrades"], a: 1 },
    { q: "International travel needs?", o: ["No ID", "Valid passport usually", "Any student card", "Domestic license alone"], a: 1 },
    { q: "IATA airport codes are?", o: ["Three letters often", "Two numbers", "Colors", "Shapes"], a: 0 },
  ],
  brands: [
    { q: "Nike logo?", o: ["Three stripes", "Swoosh", "Tiger", "Apple"], a: 1 },
    { q: "Coca-Cola brand color?", o: ["Green", "Red", "Blue", "Yellow"], a: 1 },
    { q: "McDonald's origin?", o: ["USA", "France", "Japan", "Italy"], a: 0 },
    { q: "Samsung HQ country?", o: ["Japan", "South Korea", "China", "Taiwan"], a: 1 },
    { q: "Starbucks started selling?", o: ["Tea", "Coffee beans", "Juice", "Ice cream"], a: 1 },
    { q: "Tesla named after?", o: ["President", "Nikola Tesla", "City", "River"], a: 1 },
    { q: "Hyundai from?", o: ["Japan", "South Korea", "China", "Thailand"], a: 1 },
    { q: "Apple logo fruit?", o: ["Pear", "Apple", "Orange", "Grape"], a: 1 },
  ],
  soccer: [
    { q: "Players per team on field in football?", o: ["10", "11", "9", "7"], a: 1 },
    { q: "FIFA World Cup every?", o: ["2 years", "4 years", "3 years", "5 years"], a: 1 },
    { q: "FIFA HQ city?", o: ["London", "Zurich", "Paris", "Madrid"], a: 1 },
    { q: "Red card means?", o: ["Warning", "Sent off", "Substitute", "Corner"], a: 1 },
    { q: "Penalty spot distance ~?", o: ["9 m", "11 m", "16 m", "5 m"], a: 1 },
    { q: "UEFA Champions League is?", o: ["Asian", "European clubs", "African", "South American"], a: 1 },
    { q: "Only who may use hands in box (normally)?", o: ["Striker", "Goalkeeper", "Referee", "Coach"], a: 1 },
    { q: "Offside rule mainly about?", o: ["Shirt color", "Position ahead of ball and second-last defender", "Shoe size", "Hair"], a: 1 },
  ],
  maps: [
    { q: "Capital of Japan?", o: ["Osaka", "Tokyo", "Kyoto", "Yokohama"], a: 1 },
    { q: "Capital of Canada?", o: ["Toronto", "Ottawa", "Vancouver", "Montreal"], a: 1 },
    { q: "Executive capital of South Africa (one)?", o: ["Cape Town", "Pretoria", "Johannesburg", "Durban"], a: 1 },
    { q: "Capital of Australia?", o: ["Sydney", "Canberra", "Melbourne", "Perth"], a: 1 },
    { q: "Capital of Brazil?", o: ["Rio", "Brasília", "São Paulo", "Salvador"], a: 1 },
    { q: "Administrative capital of Switzerland?", o: ["Zurich", "Bern", "Geneva", "Basel"], a: 1 },
    { q: "Capital of Turkey?", o: ["Istanbul", "Ankara", "Izmir", "Antalya"], a: 1 },
    { q: "Capital of Argentina?", o: ["Córdoba", "Buenos Aires", "Mendoza", "Rosario"], a: 1 },
  ],
  riddles: [
    { q: "The more you take, the larger it becomes?", o: ["Water", "A hole", "Light", "Food"], a: 1 },
    { q: "Has teeth but cannot bite?", o: ["Saw", "Comb", "Dog", "Snake"], a: 1 },
    { q: "Runs but never walks?", o: ["Human", "River", "Robot", "Car"], a: 1 },
    { q: "Green in field, black in market, red at home?", o: ["Apple", "Tea", "Lettuce", "Pepper"], a: 1 },
    { q: "House with no doors or windows?", o: ["Igloo", "Spider web", "Tent", "Tower"], a: 1 },
    { q: "I am my parents' child but not my siblings' brother?", o: ["Cousin", "Me (the speaker)", "Neighbor", "Friend"], a: 1 },
    { q: "Born long ago, but only a month old?", o: ["Baby", "Moon", "Star", "Year"], a: 1 },
    { q: "What has a neck but no head?", o: ["Snake", "Bottle", "Giraffe", "Turtle"], a: 1 },
  ],
  chemistry: [
    { q: "Symbol for gold?", o: ["Ag", "Au", "Fe", "Pb"], a: 1 },
    { q: "Gas that supports combustion?", o: ["Nitrogen", "Oxygen", "CO₂", "Helium"], a: 1 },
    { q: "Neutral pH?", o: ["0", "7", "14", "1"], a: 1 },
    { q: "Water is made of?", o: ["H and O", "C and N", "Na and Cl", "Fe and O"], a: 0 },
    { q: "Stomach acid mainly?", o: ["Acetic", "Hydrochloric", "Nitric", "Sulfuric"], a: 1 },
    { q: "Periodic table credited to?", o: ["Newton", "Mendeleev", "Darwin", "Einstein"], a: 1 },
    { q: "Most plastics derived from?", o: ["Plants only", "Petroleum", "Metal", "Water"], a: 1 },
    { q: "Exothermic reaction?", o: ["Absorbs heat", "Releases heat", "No change", "Only cold"], a: 1 },
  ],
  math: [
    { q: "Sum of triangle angles?", o: ["90°", "180°", "270°", "360°"], a: 1 },
    { q: "2³ equals?", o: ["6", "8", "9", "4"], a: 1 },
    { q: "Which is prime?", o: ["1", "2", "9", "15"], a: 1 },
    { q: "Circle circumference 2πr, r=3, π≈3.14 ~?", o: ["9.42", "18.84", "6", "12"], a: 1 },
    { q: "3-4-5 triangle relates to?", o: ["Pythagoras", "Euclid only", "Newton", "Archimedes only"], a: 0 },
    { q: "Any number times zero?", o: ["1", "0", "Undefined", "Same number"], a: 1 },
    { q: "Mean of 2,4,6?", o: ["3", "4", "5", "12"], a: 1 },
    { q: "Slope of horizontal line?", o: ["0", "1", "Undefined", "2"], a: 0 },
  ],
  leaders: [
    { q: "Gandhi led independence movement in?", o: ["Pakistan", "India", "Sri Lanka", "Nepal"], a: 1 },
    { q: "Nelson Mandela first Black president of?", o: ["Kenya", "South Africa", "Nigeria", "Ghana"], a: 1 },
    { q: "Churchill UK PM during?", o: ["WWI only", "WWII", "Vietnam War", "Gulf War"], a: 1 },
    { q: "Napoleon crowned Emperor of?", o: ["Spain", "France", "Russia", "Italy"], a: 1 },
    { q: "Queen Elizabeth II died in?", o: ["2016", "2022", "2025", "2010"], a: 1 },
    { q: "Martin Luther King Jr. famous speech?", o: ["I hate war", "I Have a Dream", "Go backward", "Stay silent"], a: 1 },
    { q: "Che Guevara linked to revolution in?", o: ["Cuba", "Chile only", "Mexico only", "Brazil"], a: 0 },
    { q: "Anwar Sadat peace treaty with?", o: ["Syria", "Israel", "Iraq", "Turkey"], a: 1 },
  ],
  ancient: [
    { q: "Great Pyramids built by?", o: ["Romans", "Ancient Egyptians", "Greeks", "Vikings"], a: 1 },
    { q: "Mesopotamia means land between rivers?", o: ["Nile only", "Tigris and Euphrates", "Ganges", "Amazon"], a: 1 },
    { q: "Alexander the Great died in?", o: ["Greece", "Babylon", "Rome", "Alexandria"], a: 1 },
    { q: "Romans built?", o: ["Pyramids", "Colosseum", "Taj Mahal", "Great Wall"], a: 1 },
    { q: "Hieroglyphs mainly?", o: ["China", "Ancient Egypt", "Greece", "Rome"], a: 1 },
    { q: "Phoenicians known for?", o: ["Farming only", "Trade and alphabet", "Space", "Ice"], a: 1 },
    { q: "Troy war in legend?", o: ["Spain", "Anatolia", "Italy", "Greece only"], a: 1 },
    { q: "Great Wall in?", o: ["India", "China", "Japan", "Mongolia only"], a: 1 },
  ],
  proverbs: [
    { q: "Complete: “The neighbor before the…” (Arab proverb calque)", o: ["House", "Fence", "Road", "Town"], a: 0 },
    { q: "Complete: “Patience is the key to…”", o: ["Relief", "Anger", "Wealth", "Youth"], a: 0 },
    { q: "Complete: “He who strives…” (from: whoever strives, finds)", o: ["Finds", "Sleeps", "Rests", "Leaves"], a: 0 },
    { q: "Complete: “The monkey in its mother's eye is a…”", o: ["Gazelle", "Donkey", "Tiger", "Crow"], a: 0 },
    { q: "Complete: “Stretch your legs according to your…” (coverlet proverb)", o: ["Coverlet", "Shoes", "House", "Road"], a: 0 },
    { q: "Complete: “Prevention is better than…”", o: ["Cure", "Panic", "Delay", "Silence"], a: 0 },
    { q: "Complete: “When the mind is complete…” (speech version)", o: ["Speech lessens", "Speech doubles", "Work stops", "Hope ends"], a: 0 },
    { q: "Complete: “Who seeks the heights…” (nights version)", o: ["Stays up nights", "Sleeps early", "Takes a nap", "Skips meals"], a: 0 },
  ],
  psychology: [
    { q: "Freud associated with?", o: ["Behaviorism only", "Psychoanalysis", "CBT only", "IQ tests"], a: 1 },
    { q: "Working memory capacity?", o: ["Unlimited", "Limited short-term", "Zero", "Infinite"], a: 1 },
    { q: "OCD involves?", o: ["Fear of dark", "Obsessions/compulsions", "Amnesia", "Mania only"], a: 1 },
    { q: "Positive reinforcement increases?", o: ["Punished behavior", "Rewarded behavior", "Sleep", "Anger"], a: 1 },
    { q: "EQ measures?", o: ["Running speed", "Emotional skills", "Height", "Weight"], a: 1 },
    { q: "Clinical depression often needs?", o: ["Ignore", "Professional help", "Only sports", "Travel only"], a: 1 },
    { q: "Fight-or-flight is?", o: ["Stress response", "Sleep", "Digestion", "Painting"], a: 0 },
    { q: "Rorschach test uses?", o: ["Inkblots", "Blood pressure", "Hearing", "Taste"], a: 0 },
  ],
  olympics: [
    { q: "Summer Olympics every?", o: ["2 years", "4 years", "3 years", "1 year"], a: 1 },
    { q: "Olympic flame traditionally lit in?", o: ["Olympia Greece", "Paris", "New York", "Tokyo"], a: 0 },
    { q: "Breaking debuted at Summer Olympics in?", o: ["Tokyo 2020", "Paris 2024", "LA 2028", "Never"], a: 1 },
    { q: "Gold medal color?", o: ["Silver", "Gold", "Bronze", "Green"], a: 1 },
    { q: "Olympic motto Latin?", o: ["Citius Altius Fortius", "Carpe Diem", "Veni Vidi Vici", "E Pluribus"], a: 0 },
    { q: "Winter Olympics need?", o: ["Desert", "Snow/ice sports", "Rainforest", "Cities only"], a: 1 },
    { q: "IOC headquarters?", o: ["New York", "Lausanne", "Geneva", "Paris"], a: 1 },
    { q: "First modern Olympics (1896) in?", o: ["Paris 1900", "Athens 1896", "London 1908", "Rome 1960"], a: 1 },
  ],
  inventions: [
    { q: "Telephone credited to?", o: ["Edison", "Bell", "Tesla", "Marconi"], a: 1 },
    { q: "Steam engine improved industrially by?", o: ["Newton", "James Watt", "Faraday", "Edison"], a: 1 },
    { q: "Movable-type printing Europe?", o: ["Gutenberg", "Shakespeare", "Columbus", "Galileo"], a: 0 },
    { q: "Penicillin by?", o: ["Fleming", "Pasteur", "Koch", "Einstein"], a: 0 },
    { q: "Internet roots in?", o: ["ARPANET", "Facebook", "Google", "Apple"], a: 0 },
    { q: "Wright brothers first powered flight?", o: ["1903", "1910", "1890", "1920"], a: 0 },
    { q: "Microwave oven discovery linked to?", o: ["Cooking show", "Radar research", "TV", "Phone"], a: 1 },
    { q: "Light bulb commercialized notably by?", o: ["Tesla only", "Edison (development)", "Newton", "Marconi"], a: 1 },
  ],
  horror: [
    { q: "The Shining director?", o: ["Spielberg", "Kubrick", "Carpenter", "Craven"], a: 1 },
    { q: "It novel author?", o: ["Stephen King", "Poe", "Lovecraft", "Shelley"], a: 0 },
    { q: "Freddy Krueger from?", o: ["Halloween", "A Nightmare on Elm Street", "Scream", "Friday 13th"], a: 1 },
    { q: "Psycho director?", o: ["Kubrick", "Hitchcock", "Carpenter", "Romero"], a: 1 },
    { q: "The Ring originated in?", o: ["Korea", "Japan", "Thailand", "China"], a: 1 },
    { q: "Ghostface from?", o: ["Halloween", "Scream", "Saw", "Insidious"], a: 1 },
    { q: "Night of the Living Dead year?", o: ["1958", "1968", "1978", "1988"], a: 1 },
    { q: "The Exorcist genre?", o: ["Comedy", "Horror/supernatural", "Cartoon", "Documentary"], a: 1 },
  ],
  anime: [
    { q: "Naruto about?", o: ["Pirates", "Ninjas", "Samurai", "Space"], a: 1 },
    { q: "One Piece about?", o: ["Ninjas", "Pirates", "Soccer", "School"], a: 1 },
    { q: "Dragon Ball by?", o: ["Oda", "Toriyama", "Kishimoto", "Togashi"], a: 1 },
    { q: "Death Note kills by?", o: ["Sword", "Writing name", "Poison", "Stare"], a: 1 },
    { q: "Attack on Titan Japanese title genre?", o: ["Naruto", "Shingeki no Kyojin", "Bleach", "One Piece"], a: 1 },
    { q: "Slam Dunk sport?", o: ["Soccer", "Basketball", "Swimming", "Tennis"], a: 1 },
    { q: "Detective Conan shrunk by?", o: ["Magic", "Poison", "Dream", "Training"], a: 1 },
    { q: "Hayao Miyazaki tied to?", o: ["Ghibli", "Shonen Jump", "Disney only", "Fox Kids"], a: 0 },
  ],
  mythology: [
    { q: "Zeus god of?", o: ["Sea", "Sky and thunder", "War", "Death"], a: 1 },
    { q: "Thor Norse god of?", o: ["Wisdom", "Thunder", "Sea", "Fire"], a: 1 },
    { q: "Poseidon Greek god of?", o: ["Sky", "Sea", "War", "Sun"], a: 1 },
    { q: "Odysseus hero of?", o: ["Iliad", "Odyssey", "Aeneid", "Beowulf"], a: 1 },
    { q: "Anubis head?", o: ["Hawk", "Jackal", "Lion", "Bull"], a: 1 },
    { q: "Medusa hair?", o: ["Gold", "Snakes", "Fire", "Water"], a: 1 },
    { q: "Valhalla in?", o: ["Greek", "Norse", "Egyptian", "Chinese"], a: 1 },
    { q: "Pandora's box myth origin?", o: ["Roman", "Greek", "Indian", "Norse"], a: 1 },
  ],
  dance: [
    { q: "Ballet developed strongly in?", o: ["Italy then France", "Mexico", "Canada", "Japan"], a: 0 },
    { q: "Salsa roots?", o: ["Cuba/Caribbean", "Sweden", "Russia", "Japan"], a: 0 },
    { q: "Flamenco from?", o: ["Portugal", "Spain", "France", "Italy"], a: 1 },
    { q: "Tango strongly linked to?", o: ["Argentina", "Canada", "Norway", "India"], a: 0 },
    { q: "Hip-hop dance culture began in?", o: ["New York", "Paris", "London", "Dubai"], a: 0 },
    { q: "Dabke associated with?", o: ["Levant", "Brazil", "Japan", "Australia"], a: 0 },
    { q: "Classical ballet shoes?", o: ["Sneakers", "Pointe shoes", "Boots", "Barefoot"], a: 1 },
    { q: "Samba parades famous in?", o: ["Rio", "Moscow", "Oslo", "Beijing"], a: 0 },
  ],
  architecture: [
    { q: "Burj Khalifa in?", o: ["Qatar", "UAE", "Saudi", "Kuwait"], a: 1 },
    { q: "Taj Mahal in?", o: ["Pakistan", "India", "Iran", "Bangladesh"], a: 1 },
    { q: "Leaning Tower in?", o: ["Rome", "Pisa", "Milan", "Naples"], a: 1 },
    { q: "Sagrada Família in?", o: ["Madrid", "Barcelona", "Seville", "Bilbao"], a: 1 },
    { q: "Sydney Opera House shape like?", o: ["Pyramid", "Shells/sails", "Cube", "Iron tower"], a: 1 },
    { q: "Petra in?", o: ["Egypt", "Jordan", "Lebanon", "Iraq"], a: 1 },
    { q: "Eiffel Tower material?", o: ["Wood", "Iron", "Glass only", "Clay"], a: 1 },
    { q: "Arc de Triomphe era?", o: ["Louis XIV", "Napoleonic France", "Roman Empire", "Charlemagne"], a: 1 },
  ],
  ocean: [
    { q: "Deepest ocean trench known?", o: ["Mariana", "Puerto Rico", "Java", "Japan"], a: 0 },
    { q: "Largest ocean?", o: ["Atlantic", "Pacific", "Indian", "Arctic"], a: 1 },
    { q: "Great Barrier Reef off?", o: ["Africa", "Australia", "Brazil", "India"], a: 1 },
    { q: "Earth surface water ~?", o: ["50%", "71%", "90%", "30%"], a: 1 },
    { q: "Tsunami often from?", o: ["Light wind", "Undersea quake/slide", "Moon only", "Drought"], a: 1 },
    { q: "Largest ocean animal?", o: ["Great white", "Blue whale", "Dolphin", "Seal"], a: 1 },
    { q: "Dead Sea salinity?", o: ["Fresh", "Very high", "Zero", "Sweet"], a: 1 },
    { q: "Tides mainly from?", o: ["Moon and sun", "Surface winds alone", "Sudden barometric drops", "Deep ocean currents only"], a: 0 },
  ],
  social: [
    { q: "Instagram owned by?", o: ["Google", "Meta", "Twitter", "Snap"], a: 1 },
    { q: "TikTok parent company?", o: ["ByteDance", "Meta", "Apple", "Netflix"], a: 0 },
    { q: "Twitter rebranded to?", o: ["Threads", "X", "Bluesky", "Mastodon"], a: 1 },
    { q: "WhatsApp co-founder?", o: ["Jan Koum", "Bezos", "Musk", "Gates"], a: 0 },
    { q: "Snapchat known for?", o: ["Permanent posts", "Disappearing messages", "Music only", "Shopping only"], a: 1 },
    { q: "YouTube founded ~?", o: ["2003", "2005", "2007", "2010"], a: 1 },
    { q: "LinkedIn for?", o: ["Games", "Professional networking", "Cooking", "Sports"], a: 1 },
    { q: "Reddit nickname?", o: ["Front page of the internet", "Email", "Fax", "Radio"], a: 0 },
  ],
  law: [
    { q: "Universal Declaration of Human Rights?", o: ["1945", "1948", "1950", "1960"], a: 1 },
    { q: "International Court of Justice?", o: ["New York", "The Hague", "Geneva", "Brussels"], a: 1 },
    { q: "UN main HQ?", o: ["Geneva", "New York", "Vienna", "Paris"], a: 1 },
    { q: "Innocent until?", o: ["Confession", "Proven guilty", "Jail", "Fine"], a: 1 },
    { q: "Civil law often covers?", o: ["Only theft", "Contracts and private disputes", "War", "Space only"], a: 1 },
    { q: "ICC (criminal court) in?", o: ["New York", "The Hague", "Geneva", "Rome"], a: 1 },
    { q: "Trademark protects?", o: ["Brand sign", "House", "Car", "Passport"], a: 0 },
    { q: "Arbitration alternative to?", o: ["Mandatory accounting audit", "Court trial", "Executive mediation board", "Sports tribunal"], a: 1 },
  ],
  aviation: [
    { q: "First powered flight Wright brothers?", o: ["1903", "1918", "1895", "1927"], a: 0 },
    { q: "Boeing mainly makes?", o: ["Cars", "Aircraft", "Ships", "Trains"], a: 1 },
    { q: "Black box flight recorder color often?", o: ["Black", "Bright orange", "White", "Blue"], a: 1 },
    { q: "Heathrow airport?", o: ["Paris", "London", "Berlin", "Madrid"], a: 1 },
    { q: "Autopilot helps with?", o: ["Landing only", "Flight path/altitude", "Food", "Passengers only"], a: 1 },
    { q: "Shortest path on Earth between points?", o: ["Straight on map paper", "Great circle", "Zigzag", "Random"], a: 1 },
    { q: "Concorde was?", o: ["Subsonic always", "Supersonic passenger jet", "Blimp", "Glider"], a: 1 },
    { q: "Turbofan vs propeller high speed?", o: ["Prop always better", "Turbofan more efficient high speed", "No thrust", "For boats"], a: 1 },
  ],
  currencies: [
    { q: "Euro used in?", o: ["Only UK", "Eurozone countries", "Only USA", "All South America"], a: 1 },
    { q: "Yen is currency of?", o: ["China", "Japan", "Korea", "Thailand"], a: 1 },
    { q: "Pound sterling country?", o: ["USA", "UK", "Canada", "Australia"], a: 1 },
    { q: "Swiss franc country?", o: ["Sweden", "Switzerland", "Austria", "Denmark"], a: 1 },
    { q: "Saudi riyal?", o: ["UAE", "Saudi Arabia", "Qatar", "Kuwait"], a: 1 },
    { q: "Bitcoin is?", o: ["Central bank note", "Cryptocurrency", "Gold coin", "Silver bar"], a: 1 },
    { q: "IMF headquarters?", o: ["New York", "Washington DC", "Geneva", "London"], a: 1 },
    { q: "Canadian dollar code?", o: ["CAD", "EUR", "GBP", "JPY"], a: 0 },
  ],
  language: [
    { q: "Most native speakers globally ~?", o: ["English only", "Mandarin Chinese", "Arabic only", "Swedish"], a: 1 },
    { q: "Official language of Brazil?", o: ["Spanish", "Portuguese", "English", "French"], a: 1 },
    { q: "Cyrillic script used in?", o: ["Spain", "Russia and others", "Japan", "Thailand"], a: 1 },
    { q: "Esperanto is?", o: ["Ancient language", "Constructed auxiliary language", "Dialect", "Cipher"], a: 1 },
    { q: "Arabic alphabet letters ~?", o: ["26", "28", "33", "40"], a: 1 },
    { q: "Sanskrit historically tied to?", o: ["Japan", "India", "Sweden", "Mexico"], a: 1 },
    { q: "Bilingual means?", o: ["No language", "Two languages", "Silent", "Written only"], a: 1 },
    { q: "Braille is for?", o: ["Deaf", "Blind reading", "Color", "Speed typing"], a: 1 },
  ],
  photography: [
    { q: "Aperture measured in?", o: ["ISO", "f-stop", "WB", "FPS"], a: 1 },
    { q: "ISO raises?", o: ["Shutter only", "Sensor sensitivity to light", "Color only", "Memory"], a: 1 },
    { q: "Wide-angle lens for?", o: ["Telephoto", "Expansive scenes", "Macro only", "Night only"], a: 1 },
    { q: "RAW vs JPEG?", o: ["Less data", "More editing latitude", "Video", "Audio"], a: 1 },
    { q: "Bokeh refers to?", o: ["Darkness", "Blurry background aesthetic", "Flash", "Noise"], a: 1 },
    { q: "Fast shutter freezes?", o: ["Slow motion blur", "Fast motion", "Color", "Memory"], a: 1 },
    { q: "Tripod reduces?", o: ["Color", "Camera shake", "Battery", "Lens size"], a: 1 },
    { q: "Portrait mode often uses?", o: ["Ultra-wide", "Shallow depth of field", "Fisheye", "Macro"], a: 1 },
  ],
  gems: [
    { q: "Diamond is made of?", o: ["Silicon", "Carbon", "Oxygen", "Iron"], a: 1 },
    { q: "Ruby mineral?", o: ["Emerald", "Corundum", "Opal", "Pearl"], a: 1 },
    { q: "Emerald color?", o: ["Red", "Green", "Blue", "Yellow"], a: 1 },
    { q: "Pearl from?", o: ["Plant", "Mollusk", "Volcano", "Ice"], a: 1 },
    { q: "Mohs scale measures?", o: ["Hardness", "Color", "Weight", "Clarity only"], a: 0 },
    { q: "Opal known for?", o: ["Solid color", "Play of color", "Transparent only", "Black only"], a: 1 },
    { q: "Sapphire is blue variety of?", o: ["Emerald", "Corundum", "Topaz", "Garnet"], a: 1 },
    { q: "Carat measures?", o: ["Size of box", "Gem mass", "Price only", "Age"], a: 1 },
  ],
  weather: [
    { q: "Richter scale measures?", o: ["Wind", "Earthquake magnitude", "Rain", "Temperature"], a: 1 },
    { q: "Atlantic hurricane name?", o: ["Typhoon", "Hurricane", "Monsoon", "Dust devil"], a: 1 },
    { q: "Anemometer measures?", o: ["Pressure", "Wind speed", "Humidity", "Lightning"], a: 1 },
    { q: "Lightning vs sound which faster?", o: ["Sound", "Light", "Same", "Neither"], a: 1 },
    { q: "Low pressure often brings?", o: ["Always dry", "Clouds and rain possible", "Only polar snow", "Nothing"], a: 1 },
    { q: "100% humidity near?", o: ["Saturation", "Total dryness", "Freezing", "Zero rain"], a: 0 },
    { q: "Fog is cloud?", o: ["High", "At ground", "Space", "Ocean"], a: 1 },
    { q: "Absolute zero Kelvin 0 equals?", o: ["0°C", "-273.15°C", "100°C", "32°F"], a: 1 },
  ],
  dinosaurs: [
    { q: "T-Rex diet?", o: ["Plants", "Carnivore", "Fish only", "Insects only"], a: 1 },
    { q: "Dinosaur extinction famous event ~?", o: ["65 million years ago", "6500 years", "650 years", "6.5 years"], a: 0 },
    { q: "Fossils in rocks?", o: ["Air", "Sedimentary", "Ice only", "Plastic"], a: 1 },
    { q: "Birds descended from?", o: ["No", "Theropod dinosaurs", "Fish", "Amphibians only"], a: 1 },
    { q: "Triceratops had horns?", o: ["None", "Three on face", "One", "Ten"], a: 1 },
    { q: "Long-neck giants called?", o: ["Raptors", "Sauropods", "Birds", "Mammals"], a: 1 },
    { q: "Dinosaurs lived in?", o: ["Today only", "Mesozoic mainly", "Ice age only", "Future"], a: 1 },
    { q: "Amber can preserve?", o: ["Water", "Ancient insects", "Gold", "Plastic"], a: 1 },
  ],
  comics: [
    { q: "Batman city?", o: ["Metropolis", "Gotham", "Central City", "Star City"], a: 1 },
    { q: "MCU stands for?", o: ["Batman", "Marvel Cinematic Universe", "Superman only", "Tintin"], a: 1 },
    { q: "Stan Lee role?", o: ["Painter only", "Writer/editor pioneer", "Actor only", "Musician"], a: 1 },
    { q: "Spider-Man alter ego?", o: ["Bruce Wayne", "Peter Parker", "Clark Kent", "Tony Stark"], a: 1 },
    { q: "Manga from?", o: ["Korea", "Japan", "China", "France"], a: 1 },
    { q: "DC vs Marvel?", o: ["Same company", "Two publishers", "Sports", "Food"], a: 1 },
    { q: "Asterix origin?", o: ["USA", "France/Belgium", "Japan", "Egypt"], a: 1 },
    { q: "Calvin and Hobbes format?", o: ["Anime", "Comic strip", "Novel", "Film"], a: 1 },
  ],
  kuwait_restaurants: [
    { q: "Global fast-food brands are usually known for?", o: ["Logos and standardized menus", "Only raw grain sales", "No printed menus ever", "Bookbinding"], a: 0 },
    { q: "Popular seafood restaurants typically serve?", o: ["Fish and shellfish dishes", "Only wheat berries", "Only soda", "No food"], a: 0 },
    { q: "Mall cafés differ from full restaurants by often offering?", o: ["Drinks and quick bites", "Only wedding banquets", "Night fishing", "Auto repair"], a: 0 },
    { q: "A restaurant chain usually means?", o: ["Multiple locations under one brand", "Exactly one location forever", "Vegetable wholesale", "Hay storage"], a: 0 },
    { q: "A locally famous restaurant may be known for?", o: ["A signature dish or style", "Never opening", "No menu at all", "Banning customers"], a: 0 },
    { q: "A coastal fish market mainly sells?", o: ["Fresh seafood", "Tires only", "Furniture only", "Rare books"], a: 0 },
    { q: "Heritage-market eateries often blend?", o: ["Traditional vibe and local food", "Ice skating", "Polar whale hunting", "Japanese rice paddies"], a: 0 },
    { q: "A mall food court clusters?", o: ["Many eateries in one area", "A central bank", "A surgery ward", "A courthouse"], a: 0 },
  ],
  kuwait_malls: [
    { q: "A regional shopping center often combines retail with?", o: ["Parking, A/C, dining, cinema", "Desert farming only", "Shipbuilding", "Air traffic control"], a: 0 },
    { q: "A traditional souk differs from a modern mall mainly by?", o: ["Open lanes and smaller shops", "Single sealed skyscraper only", "No vendors", "Underwater tunnels only"], a: 0 },
    { q: "Food courts in malls are?", o: ["Cluster of restaurants with shared seating", "Weapons depot", "Livestock pens", "Olympic pools only"], a: 0 },
    { q: "Retail tenants usually pay the landlord?", o: ["Rent or revenue share", "Personal visitor taxes", "Nothing ever", "Only in barter fish"], a: 0 },
    { q: "Interior mall maps help shoppers?", o: ["Find units and exits", "Predict earthquakes", "Mint currency", "Repair aircraft"], a: 0 },
    { q: "Mixed retail-entertainment venues target?", o: ["Families and day trips", "Oil refineries", "Container ports", "Freight only"], a: 0 },
    { q: "Very large malls may include?", o: ["Cinemas and play zones", "Only grain silos", "Cattle auctions only", "Nuclear plants"], a: 0 },
    { q: "Escalators in malls mainly move people?", o: ["Between floors", "Across oceans", "Through customs", "Into vaults"], a: 0 },
  ],
  kuwait_parliament: [
    { q: "Kuwait's National Assembly is the?", o: ["Legislative authority", "Executive branch", "Judiciary", "Municipality"], a: 0 },
    { q: "Usually elected assembly seats are?", o: ["50", "30", "75", "100"], a: 0 },
    { q: "Assembly building is in?", o: ["Kuwait City", "Jahra", "Ahmadi", "Fahaheel"], a: 0 },
    { q: "A key parliamentary oversight tool is?", o: ["Interpellation", "Sports arbitration", "Urban zoning", "Trade license"], a: 0 },
    { q: "Kuwait's constitution was issued in?", o: ["1962", "1951", "1979", "1988"], a: 0 },
    { q: "Parliamentary elections are organized by?", o: ["Electoral districts", "Full appointments", "Lottery", "Private voting apps"], a: 0 },
    { q: "Assembly sessions are usually covered by?", o: ["Official media", "Fax only", "Mail only", "Billboards"], a: 0 },
    { q: "Passing laws typically needs?", o: ["Assembly approval and constitutional process", "A private company vote", "Municipal vote only", "Club vote"], a: 0 },
  ],
  kuwait_foods: [
    { q: "A famous Kuwaiti dish is?", o: ["Machboos", "Sushi", "Taco", "Pizza"], a: 0 },
    { q: "Harees is often made from?", o: ["Wheat and meat", "Rice only", "Fish only", "Potato"], a: 0 },
    { q: "Marqooq usually features?", o: ["Thin dough with stew", "Pasta only", "Toasted bread", "Fruit salad"], a: 0 },
    { q: "Luqaimat is generally a?", o: ["Dessert", "Main course", "Salad", "Soup"], a: 0 },
    { q: "Mutabbaq zubaidi is linked with?", o: ["Fish", "Chicken", "Beef", "Desserts"], a: 0 },
    { q: "Aish mummawash combines?", o: ["Rice and lentils", "Rice and pasta", "Wheat and meat", "Bread and dates"], a: 0 },
    { q: "Tashreeb typically includes?", o: ["Bread with broth", "Raw fish", "Pasta", "Cold sweets"], a: 0 },
    { q: "In diwaniyas, people often serve?", o: ["Coffee and dates", "Green tea only", "Juice only", "Soup"], a: 0 },
  ],
  kuwait_cafes: [
    { q: "A well-known cafe-heavy area is?", o: ["Salmiya", "Wafra only", "Islands only", "Abdali only"], a: 0 },
    { q: "Most common cafe drink is?", o: ["Coffee", "Soup", "Broth", "Milk only"], a: 0 },
    { q: "Waterfront cafes are common near?", o: ["Marina and corniche", "Industrial zones only", "Airport", "Farms"], a: 0 },
    { q: "Cafe gatherings are usually?", o: ["Social", "Judicial", "Medical", "Athletic only"], a: 0 },
    { q: "Mall cafes are usually in?", o: ["Food and dining zones", "Warehouses", "Parking lots", "Roof only"], a: 0 },
    { q: "Specialty cafe growth is tied to?", o: ["Modern coffee culture", "Agriculture", "Fishing", "Aviation"], a: 0 },
    { q: "Iced latte is a?", o: ["Cold drink", "Dessert", "Main dish", "Salad"], a: 0 },
    { q: "Studying in cafes is common due to?", o: ["Wi-Fi and seating", "Olympic pools", "Labs", "Hospitals"], a: 0 },
  ],
  kuwait_towers: [
    { q: "Most iconic towers in Kuwait are?", o: ["Kuwait Towers", "Leaning Tower", "Eiffel Tower", "Clock Tower"], a: 0 },
    { q: "Kuwait Towers are on the?", o: ["Coast in Kuwait City", "Jahra inland", "Ahmadi desert", "Failaka center"], a: 0 },
    { q: "Al Hamra Tower is known as?", o: ["One of the tallest towers", "An airport", "A refinery", "A museum"], a: 0 },
    { q: "Kuwait Towers symbolize?", o: ["Modern city identity", "Farming", "Railway", "Forests"], a: 0 },
    { q: "Tower viewing decks offer?", o: ["Panoramic views", "Diving trips", "Skiing", "Flying"], a: 0 },
    { q: "Their design reflects?", o: ["Kuwaiti architectural identity", "Rural European style", "Only Japanese style", "Pharaonic style"], a: 0 },
    { q: "Photos by the towers are common on?", o: ["National occasions", "Court sessions", "Farm visits", "School exams"], a: 0 },
    { q: "Tourism category of the towers?", o: ["Landmark attraction", "Oil field", "Seaport", "Airport"], a: 0 },
  ],
  kuwait_celebrities: [
    { q: "Abdullah Al-Ruwaished is famous in?", o: ["Kuwaiti singing", "Medicine", "Engineering", "Basketball"], a: 0 },
    { q: "Hayat Al-Fahad is known for?", o: ["Drama acting", "Football", "Aviation", "Economics"], a: 0 },
    { q: "Suad Abdullah is one of Kuwait's famous?", o: ["Actresses", "Physicists", "Pilots", "Athletes"], a: 0 },
    { q: "Dawood Hussein is known for?", o: ["Acting", "Swimming", "Lab science", "Architecture"], a: 0 },
    { q: "Faiq Abduljaleel is notable in?", o: ["Poetry", "Boxing", "Veterinary science", "Physics"], a: 0 },
    { q: "Popular influencer platforms in Kuwait?", o: ["Snapchat and Instagram", "Fax only", "Radio only", "Print only"], a: 0 },
    { q: "Kuwaiti celebrities are often visible in?", o: ["Media and social platforms", "Oil sector only", "Geology only", "Agriculture only"], a: 0 },
    { q: "This category focuses on?", o: ["Kuwaiti public figures", "District names", "Global food", "Olympic sports"], a: 0 },
  ],
  kuwait_landmarks: [
    { q: "Al-Mubarakiya is a?", o: ["Heritage landmark market", "Oil zone", "Military base", "Farm"], a: 0 },
    { q: "The Grand Mosque is in?", o: ["Kuwait City", "Fahaheel", "Jahra", "Wafra"], a: 0 },
    { q: "Bait Al-Sadu represents?", o: ["Kuwaiti heritage", "Aviation", "Heavy industry", "Nuclear science"], a: 0 },
    { q: "Sheikh Jaber Al-Ahmad Cultural Centre is a?", o: ["Cultural landmark", "Port", "Airport", "Refinery"], a: 0 },
    { q: "Failaka Island is known for?", o: ["Archaeology and tourism", "Forests", "Snow", "High mountains"], a: 0 },
    { q: "Kuwait Towers are part of?", o: ["Kuwait landmarks", "Oil infrastructure", "Factories", "Universities"], a: 0 },
    { q: "The Red Palace is in?", o: ["Jahra", "Hawalli", "Ahmadi", "Salmiya"], a: 0 },
    { q: "The waterfront is mainly a?", o: ["Leisure landmark", "Factory", "Airport", "Rail station"], a: 0 },
  ],
  kuwait_areas: [
    { q: "How many governorates in Kuwait?", o: ["6", "4", "8", "10"], a: 0 },
    { q: "Salmiya belongs to which governorate?", o: ["Hawalli", "Capital", "Jahra", "Ahmadi"], a: 0 },
    { q: "Jahra area belongs to?", o: ["Jahra Governorate", "Capital", "Farwaniya", "Mubarak Al-Kabeer"], a: 0 },
    { q: "Fahaheel is in?", o: ["Ahmadi Governorate", "Hawalli", "Capital", "Jahra"], a: 0 },
    { q: "Mubarak Al-Kabeer is a?", o: ["Kuwaiti governorate", "Country", "Island", "Street only"], a: 0 },
    { q: "Capital Governorate includes?", o: ["Kuwait City", "Wafra", "Abdali", "Failaka only"], a: 0 },
    { q: "Farwaniya is generally known for?", o: ["High population density", "No residents", "Snow mountains", "Forests"], a: 0 },
    { q: "Ahmadi is historically linked to?", o: ["Oil sector", "Rain-fed farming", "Timber industry", "Gold mining"], a: 0 },
  ],
  kuwait_parks: [
    { q: "Public parks are generally good for?", o: ["Family recreation", "Oil refining", "Court hearings", "Aircraft repair"], a: 0 },
    { q: "A waterfront green promenade is mainly for?", o: ["Walking and leisure", "Mining", "Military port use", "Airport ops"], a: 0 },
    { q: "City parks usually include?", o: ["Benches and kids areas", "Runways", "Oil rigs", "Rail lines"], a: 0 },
    { q: "In summer, park visits are best at?", o: ["Evening", "Midday", "Late night only", "Dawn only"], a: 0 },
    { q: "Neighborhood parks mainly serve?", o: ["Local residents", "Maritime shipping", "Tax collection", "Mining"], a: 0 },
    { q: "A common park activity is?", o: ["Walking", "Deep diving", "Snow skiing", "Formula racing"], a: 0 },
    { q: "Planting trees in parks helps?", o: ["Improve quality of life", "Increase noise", "Remove shade", "Reduce space use"], a: 0 },
    { q: "Parks are part of a city's?", o: ["Leisure infrastructure", "Refineries", "Commercial ports", "Mines"], a: 0 },
  ],
  kuwait_terms: [
    { q: "In Kuwaiti Arabic, “shlonak” means?", o: ["How are you?", "What's your name?", "Where do you live?", "When are you traveling?"], a: 0 },
    { q: "The word “waid” means?", o: ["A lot / very", "A little", "Cold", "Far"], a: 0 },
    { q: "“Eshda'wa” is commonly used as?", o: ["Come on / why so much?", "Formal confirmation", "Morning greeting", "Farewell"], a: 0 },
    { q: "“Desh” in Kuwaiti dialect means?", o: ["Enter", "Exit", "Sit", "Run"], a: 0 },
    { q: "“Alheen” means?", o: ["Now", "Yesterday", "Next year", "Much later"], a: 0 },
    { q: "“Mo shart” means?", o: ["Not necessarily", "Always required", "Forbidden", "Impossible"], a: 0 },
    { q: "“Ya'teek al-'afiya” is usually said for?", o: ["Thanks and goodwill", "Threatening", "Denial", "Formal refusal"], a: 0 },
    { q: "“Zain” in Kuwaiti Arabic usually means?", o: ["Good / fine", "Bad", "Tall", "Tired"], a: 0 },
  ],
  boardgames: [
    { q: "Chess board squares?", o: ["64", "81", "100", "49"], a: 0 },
    { q: "Monopoly theme?", o: ["Cooking", "Real estate trading", "Sports", "Space"], a: 1 },
    { q: "Scrabble uses?", o: ["Numbers", "Letter tiles", "Colors", "Dance"], a: 1 },
    { q: "Risk uses?", o: ["Cards only", "Dice and world map", "Screen", "Ball"], a: 1 },
    { q: "Go originated in?", o: ["Europe", "East Asia", "USA", "South Africa"], a: 1 },
    { q: "Dungeons & Dragons is?", o: ["Board race", "Tabletop RPG", "Cooking", "Music"], a: 1 },
    { q: "Jenga pieces?", o: ["Plastic", "Wooden blocks", "Metal", "Glass"], a: 1 },
    { q: "Clue/Cluedo is?", o: ["Soccer", "Murder mystery deduction", "Chess", "Poker"], a: 1 },
  ],
};
